Repository CodeForAfricaLabs/sensors.AFRICA-SeaSensors-Map, pull requests merged in 2019-05, with the labels that each got.

#7 [Setup] Add CNAME
  docs/CNAME
  package.json
  webpack.config.js
Labels: enhancement

#5 Add detection radius of sensors
  .gitignore
  .prettierrc.json
  docs/CNAME
  docs/assets/favicon/manfest.json
  docs/assets/js/bundle.js
  docs/index.html
  eslintrc.json
  package.json
  src/js/main.js
  webpack.config.js
  yarn.lock
Labels: enhancement

#8 Remove console.log
  src/js/main.js
Labels: bug

#10 [SeaSensors][Map] Add counter
  docs/assets/css/style.css
  docs/assets/js/bundle.js
  docs/index.html
  src/js/main.js
Labels: enhancement

#14 [SeaSensors.AFRICA][Map] Add days to filter box
  docs/assets/css/style.css
  docs/assets/js/bundle.js
  docs/index.html
  src/js/blastData.js
  src/js/main.js
Labels: enhancement

#15 [Sensors.AFRICA][Map] Improve design
  docs/assets/css/style.css
  docs/index.html
  src/js/main.js
Labels: bug, enhancement

#16 [Map] Fix broken link
  .gitignore
  docs/assets/js/bundle.js
Labels: bug

#17 [Map]Update filter functionality
  docs/assets/js/bundle.js
  src/js/main.js
Labels: bug
